### ISSUE TITLE
Prettier does not use our eslint-settings

### ISSUE THREAD

**Issue by Naartti** [Teachiq/eslint-config#1]
I followed the guide in the README and had to add two settings to `.vscode/settings.json` 
```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true
}
```

Though, when saving it looks like it first formats correctly (with standard-js) but then adds semi-colons (probably air-bnb). Am I missing some settings?

**Comment by vilbergs** [comment]
You are right that these settings are required in order to get the vscode formatting to work I'll add it to the readme
